//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDEF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Crickter
    {
        
        public int Cid { get; set; }
        [Required(ErrorMessage ="Crickter Name is Required !!")]
        [DisplayName("Crickter Name")]
        public string Cname { get; set; }
        [Required(ErrorMessage ="Crickter Address is Required !!")]
        [DisplayName("Crickter Address")]
        public string Caddress { get; set; }
        [Required(ErrorMessage ="Crickter Gender is Required !!")]
        [DisplayName("Crickter Gender")]
        public string Cgender { get; set; }
    }
}
